// <auto-generated />
using System;
using ATwo.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATwo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATwo.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Degree")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Hrs")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MinDegree")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("depatrmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("depatrmentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ATwo.Models.CourseResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Degree")
                        .HasColumnType("float");

                    b.Property<int?>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("traineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courseId");

                    b.HasIndex("traineeId");

                    b.ToTable("CourseResults");
                });

            modelBuilder.Entity("ATwo.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ATwo.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("depatrmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courseId");

                    b.HasIndex("depatrmentId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("ATwo.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("depatrmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("depatrmentId");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("ATwo.Models.Course", b =>
                {
                    b.HasOne("ATwo.Models.Department", "Department")
                        .WithMany("Course")
                        .HasForeignKey("depatrmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ATwo.Models.CourseResults", b =>
                {
                    b.HasOne("ATwo.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("courseId");

                    b.HasOne("ATwo.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("traineeId");

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("ATwo.Models.Instructor", b =>
                {
                    b.HasOne("ATwo.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATwo.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("depatrmentId");

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ATwo.Models.Trainee", b =>
                {
                    b.HasOne("ATwo.Models.Department", "Department")
                        .WithMany("Trainee")
                        .HasForeignKey("depatrmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ATwo.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("ATwo.Models.Department", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("Instructors");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("ATwo.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
